FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /scrib-server -ldflags="-s -w" ./cmd/scrib-server

FROM gcr.io/distroless/static:nonroot
COPY --from=build /scrib-server /scrib-server
USER nonroot:nonroot
ENTRYPOINT ["/scrib-server"]
