package telemetry

import "github.com/solanyn/mono/line/internal/storage"

func (f *Frame) ToRow() storage.TelemetryRow {
	return storage.TelemetryRow{
		PacketID:    f.PacketID,
		PosX:        f.PosX,
		PosY:        f.PosY,
		PosZ:        f.PosZ,
		VelX:        f.VelX,
		VelY:        f.VelY,
		VelZ:        f.VelZ,
		RotPitch:    f.RotPitch,
		RotYaw:      f.RotYaw,
		RotRoll:     f.RotRoll,
		AngVelX:     f.AngVelX,
		AngVelY:     f.AngVelY,
		AngVelZ:     f.AngVelZ,
		RideHeight:  f.RideHeight,
		RPM:         f.RPM,
		FuelLevel:   f.FuelLevel,
		FuelCap:     f.FuelCap,
		Speed:       f.Speed,
		Boost:       f.Boost,
		OilPressure: f.OilPressure,
		WaterTemp:   f.WaterTemp,
		OilTemp:     f.OilTemp,
		TireTempFL:  f.TireTempFL,
		TireTempFR:  f.TireTempFR,
		TireTempRL:  f.TireTempRL,
		TireTempRR:  f.TireTempRR,
		SuspFL:      f.SuspFL,
		SuspFR:      f.SuspFR,
		SuspRL:      f.SuspRL,
		SuspRR:      f.SuspRR,
		WheelFL:     f.WheelFL,
		WheelFR:     f.WheelFR,
		WheelRL:     f.WheelRL,
		WheelRR:     f.WheelRR,
		TireRadFL:   f.TireRadFL,
		TireRadFR:   f.TireRadFR,
		TireRadRL:   f.TireRadRL,
		TireRadRR:   f.TireRadRR,
		CurrentLap:  int32(f.CurrentLap),
		TotalLaps:   int32(f.TotalLaps),
		BestLap:     f.BestLap,
		LastLap:     f.LastLap,
		CurrentTime: f.CurrentTime,
		Throttle:    int32(f.Throttle),
		Brake:       int32(f.Brake),
		Steering:    int32(f.Steering),
		Gear:        int32(f.Gear),
		CarID:       f.CarID,
		Flags:       int32(f.Flags),
		TimeOfDay:   f.TimeOfDay,
	}
}
