load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "lib",
    srcs = glob(["*.go"]),
    importpath = "github.com/solanyn/mono/cronprint",
    deps = [
        "@com_github_robfig_cron_v3//:cron",
    ],
    visibility = ["//visibility:public"],
)

go_binary(
    name = "cronprint",
    embed = [":lib"],
    visibility = ["//visibility:public"],
)